### ISSUE TITLE
Something about Supplementary Figure 18

### ISSUE THREAD

**Issue by zhengluo-zz** [Xiaoming8102/WheatPangenome#1]
To Whom It May Concern:
While reading your [article,](https://www.nature.com/articles/s41586-024-08277-0#Sec39) I came across a reference to "Supplementary Fig. 18" in the Detection of PAVs on 1RS translocations section. However, I was unable to locate this figure in the supplementary materials. Could you kindly clarify if it might be missing or referenced differently?

**Comment by xiexxm** [comment]
Dear zhengluo,
Thank you for bringing to our attention the discrepancy regarding "Supplementary Fig. 18" mentioned in the Detection of PAVs on 1RS translocations section of our article. We appreciate your careful reading and feedback.
The reason for the missing figure is that during the editing and proofreading process of the article, certain supplementary figures, including "Supplementary Fig. 18," were omitted to streamline the content and reduce the overall length. Unfortunately, the reference to this omitted figure was not updated in the main text.
To address this issue, I have attached "Supplementary Fig. 18" to this response for your reference. Please find the figure included below. If you have any further questions or require additional clarification, please do not hesitate to reach out to me.
Thank you for your understanding and continued interest in our research.
![image_23](https://github.com/user-attachments/assets/3b4f672b-be54-493f-96e0-a7c9aab77d02)

**Comment by zhengluo-zz** [comment]
Thanks！！！
